# Generated by Django 3.0.7 on 2020-06-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priceprediction', '0002_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
